# Generated by Django 3.2.13 on 2022-05-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("userposts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="userID",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.usermodel",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
