# Generated by Django 3.2.13 on 2022-05-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userposts", "0003_alter_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
