# Generated by Django 3.2.13 on 2022-05-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userposts", "0004_remove_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="userID",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
